### ISSUE TITLE
jeconsultetelechargemesdonneesdeconsommation

### ISSUE THREAD

**Issue by empierre** [Asdepique777/jeedom_linky#1]
Bonjour,

  L'URL n'existe plus, comment accéder aux informations qui semblent asynchrone (demande extract puis récupération dans les fichiers du résultat) ?

**Comment by empierre** [comment]
2017-09-13 22:46:53,435 logging in as prenom.nom@mail.com...
2017-09-13 22:46:53,440 Starting new HTTPS connection (1): espace-client-connexion.erdf.fr
2017-09-13 22:46:53,621 logged in successfully!
2017-09-13 22:46:53,622 retreiving data...
2017-09-13 22:46:53,625 Starting new HTTPS connection (1): espace-client-particuliers.erdf.fr
Traceback (most recent call last):
  File ".//linky_json.py", line 189, in <module>
    main()
  File ".//linky_json.py", line 139, in main
    res_year = linky.get_data_per_year(token)
  File "/home/in/domoticz-veolia-eau/jeedom_linky/linky.py", line 67, in get_data_per_year
    return _get_data(token, 'urlCdcAn')
  File "/home/in/domoticz-veolia-eau/jeedom_linky/linky.py", line 92, in _get_data
    return req.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by xavrr** [comment]
I forked and made some  changes to allow this script to work after Enedis web interface updates... https://github.com/xavrr/jeedom_linky

**Comment by Asdepique777** [comment]
Hi all,

Sorry for the delay, thanks for your modifications.
Enedis changed their website again, so I will push another version of the script. 
This works fine again on 07th November 2017.

**Comment by empierre** [comment]
thanks for the update, updated my version from this, I'm no python ...
also think of hiding the bot origin:
session.headers = {
                'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Mobile Safari/537.36',
                'Accept-Language':'fr,fr-FR;q=0.8,en;q=0.6',
                'Accept-Encoding':'gzip, deflate',
                'Accept':'application/json, text/javascript, */*; q=0.01'}
