### ISSUE TITLE
ImportError: No module named 'requests'

### ISSUE THREAD

**Issue by bilyboy785** [Asdepique777/jeedom_linky#4]
Salut !

Petite erreur avec ton script malheureusement : 

Traceback (most recent call last):
  File ".//linky_json.py", line 25, in <module>
    import linky
  File "/var/www/html/plugins/script/core/ressources/linky/linky.py", line 25, in <module>
    import requests
ImportError: No module named 'requests'

Autre erreur : 
ImportError: No module named 'requests'
Traceback (most recent call last):
  File ".//linky_json.py", line 26, in <module>
    from dateutil.relativedelta import relativedelta
ImportError: No module named dateutil.relativedelta

Egalement, j'ai vu que mon Jeedom installé sur Debian 9.3 est sur Python2.7, or  tu exécute ton script en python3 par défaut.

**Comment by empierre** [comment]
il te manque un module:
 python3-requests

regarde ici:https://github.com/empierre/domoticz_linky

**Comment by Xanatos00** [comment]
le package html est propre à python 3
pour python 2.7 on peut le remplacer par HTMLParser et modifier comme suit:
    if res['etat'] and res['etat']['valeur'] == 'erreur' and res['etat']['erreurText']:
        raise LinkyServiceException(HTMLParser.HTMLParser().unescape(res['etat']['erreurText']))

**Comment by zesk06** [comment]
Salut,
tu dois installer le module requests et python-dateutils

avec pip: 

```bash
pip install requests python-dateutil
```
Tu peux voir https://github.com/Asdepique777/jeedom_linky/pull/8
